### ISSUE TITLE
crash when using 'keys' with no options

### ISSUE THREAD

**Issue by zswanson** [chroju/parade#6]
Documentation for v 0.3.0 says:

```
If no argument is given, all keys will be retrieved.

$ parade keys
/service1/dev/key1   Type: String
/service1/dev/key2   Type: String
/service1/prod/key3  Type: SecureString
...
```

If I try that however the command crashes. Running 0.3.0 on MacOS BigSur 11.2.1

09:05 $ parade keys
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/chroju/parade/cmd.initializeCredential(0x1b28360, 0x1b5e8a8, 0x0, 0x0, 0x0, 0x0)
	/Users/zswanson/go/pkg/mod/github.com/chroju/parade@v0.3.0/cmd/root.go:117 +0x13d
github.com/spf13/cobra.(*Command).execute(0x1b28360, 0x1b5e8a8, 0x0, 0x0, 0x1b28360, 0x1b5e8a8)
	/Users/zswanson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:815 +0x530
github.com/spf13/cobra.(*Command).ExecuteC(0x1b27960, 0x1b5e62c, 0x16ec5e3, 0x8)
	/Users/zswanson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/zswanson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/chroju/parade/cmd.Execute(0x17e9500, 0xc000010018, 0x17e9500, 0xc000010020, 0xffffffff, 0xc0000360b8)
	/Users/zswanson/go/pkg/mod/github.com/chroju/parade@v0.3.0/cmd/root.go:109 +0x1eb
main.main()
	/Users/zswanson/go/pkg/mod/github.com/chroju/parade@v0.3.0/main.go:10 +0x4a

**Comment by chroju** [comment]
@zswanson 
Thanks. Fix it in [v0.3.1](https://github.com/chroju/parade/releases/tag/v0.3.1) .
